### ISSUE TITLE
Error on Forge Servers

### ISSUE THREAD

**Issue by ZandercraftGames** [Naetheline/KingVillager#8]
The following error occurs when using the mod on a forge server:
```
[15:02:34] [main/INFO] [STDERR/]: [softcat.kingvillager.Registration.ProfessionRegistration:injectWorkstation:81]: java.lang.NoSuchMethodException: net.minecraft.village.PointOfInterestType.registerBlockStates(net.minecraft.village.PointOfInterestType)
[15:02:34] [main/INFO] [STDERR/]: [softcat.kingvillager.Registration.ProfessionRegistration:injectWorkstation:81]:      at java.base/java.lang.Class.getDeclaredMethod(Class.java:2633)
[15:02:34] [main/INFO] [STDERR/]: [softcat.kingvillager.Registration.ProfessionRegistration:injectWorkstation:81]:      at softcat.kingvillager.Registration.ProfessionRegistration.injectWorkstation(ProfessionRegistration.java:67)
[15:02:34] [main/INFO] [STDERR/]: [softcat.kingvillager.Registration.ProfessionRegistration:injectWorkstation:81]:      at softcat.kingvillager.Registration.ProfessionRegistration.registerProfession(ProfessionRegistration.java:53)
[15:02:34] [main/INFO] [STDERR/]: [softcat.kingvillager.Registration.ProfessionRegistration:injectWorkstation:81]:      at net.minecraftforge.eventbus.ASMEventHandler_4_ProfessionRegistration_registerProfession_Register.invoke(.dynamic)
[15:02:34] [main/INFO] [STDERR/]: [softcat.kingvillager.Registration.ProfessionRegistration:injectWorkstation:81]:      at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
[15:02:34] [main/INFO] [STDERR/]: [softcat.kingvillager.Registration.ProfessionRegistration:injectWorkstation:81]:      at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
[15:02:34] [main/INFO] [STDERR/]: [softcat.kingvillager.Registration.ProfessionRegistration:injectWorkstation:81]:      at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
[15:02:34] [main/INFO] [STDERR/]: [softcat.kingvillager.Registration.ProfessionRegistration:injectWorkstation:81]:      at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120)
[15:02:34] [main/INFO] [STDERR/]: [softcat.kingvillager.Registration.ProfessionRegistration:injectWorkstation:81]:      at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121)
[15:02:34] [main/INFO] [STDERR/]: [softcat.kingvillager.Registration.ProfessionRegistration:injectWorkstation:81]:      at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800)
[15:02:34] [main/INFO] [STDERR/]: [softcat.kingvillager.Registration.ProfessionRegistration:injectWorkstation:81]:      at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56)
[15:02:34] [main/INFO] [STDERR/]: [softcat.kingvillager.Registration.ProfessionRegistration:injectWorkstation:81]:      at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40)
[15:02:34] [main/INFO] [STDERR/]: [softcat.kingvillager.Registration.ProfessionRegistration:injectWorkstation:81]:      at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:243)
[15:02:34] [main/INFO] [STDERR/]: [softcat.kingvillager.Registration.ProfessionRegistration:injectWorkstation:81]:      at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:230)
[15:02:34] [main/INFO] [STDERR/]: [softcat.kingvillager.Registration.ProfessionRegistration:injectWorkstation:81]:      at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:196)
[15:02:34] [main/INFO] [STDERR/]: [softcat.kingvillager.Registration.ProfessionRegistration:injectWorkstation:81]:      at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44)
[15:02:34] [main/INFO] [STDERR/]: [softcat.kingvillager.Registration.ProfessionRegistration:injectWorkstation:81]:      at net.minecraft.server.Main.main(Main.java:95)
[15:02:34] [main/INFO] [STDERR/]: [softcat.kingvillager.Registration.ProfessionRegistration:injectWorkstation:81]:      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:02:34] [main/INFO] [STDERR/]: [softcat.kingvillager.Registration.ProfessionRegistration:injectWorkstation:81]:      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
[15:02:34] [main/INFO] [STDERR/]: [softcat.kingvillager.Registration.ProfessionRegistration:injectWorkstation:81]:      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:02:34] [main/INFO] [STDERR/]: [softcat.kingvillager.Registration.ProfessionRegistration:injectWorkstation:81]:      at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[15:02:34] [main/INFO] [STDERR/]: [softcat.kingvillager.Registration.ProfessionRegistration:injectWorkstation:81]:      at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51)
[15:02:34] [main/INFO] [STDERR/]: [softcat.kingvillager.Registration.ProfessionRegistration:injectWorkstation:81]:      at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[15:02:34] [main/INFO] [STDERR/]: [softcat.kingvillager.Registration.ProfessionRegistration:injectWorkstation:81]:      at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[15:02:34] [main/INFO] [STDERR/]: [softcat.kingvillager.Registration.ProfessionRegistration:injectWorkstation:81]:      at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[15:02:34] [main/INFO] [STDERR/]: [softcat.kingvillager.Registration.ProfessionRegistration:injectWorkstation:81]:      at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[15:02:34] [main/INFO] [STDERR/]: [softcat.kingvillager.Registration.ProfessionRegistration:injectWorkstation:81]:      at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[15:02:34] [main/INFO] [STDERR/]: [softcat.kingvillager.Registration.ProfessionRegistration:injectWorkstation:81]:      at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
[15:02:34] [main/INFO] [STDERR/]: [softcat.kingvillager.Registration.ProfessionRegistration:injectWorkstation:81]:      at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
[15:02:34] [main/INFO] [STDERR/]: [softcat.kingvillager.Registration.ProfessionRegistration:injectWorkstation:81]:      at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
```

Server forge version: forge-1.16.5-36.0.42.jar
Minecraft version: 1.16.5

**Comment by drakray** [comment]
I got the same thing, it's the only STDERR in my logs :'(
https://pastebin.com/WQZbujPV
